name: environment
on: push

jobs:
  Organization:
    runs-on: ubuntu-latest
    steps:
      - name: get Organization level secrets & variables
        run: |
          echo ${{ vars.LEVEL }}
          echo ${{ secrets.SECRET }}

  environment-dev:
    runs-on: ubuntu-latest
    # 환경을 직접 정의하여 관리
    # dev 라는 environment에 정의된 환경변수와 secret을 사용한다
    environment: dev
    steps:
      - name: get Environment level secrets & variables
        run: |
          echo ${{ vars.LEVEL }}
          echo ${{ secrets.SECRET }}
