name: matrix
on: push

jobs:
  use-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [12,14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: use matrix
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.version }}