name: string-function.yml
on:
  push

jobs:
  ends-with:
    runs-on: ubuntu-latest
    steps:
      - name: endsWith with true
        if: endsWith('github actions', 'ions' )
        run: echo git is true
      - name: endsWith with false
        if: endsWith('github actions', 'test' )
        run: echo test is false
        
