name: string-function.yml
on:
  push

jobs:
  contains:
    runs-on: ubuntu-latest
    steps:
      - name: contains with true
        if: contains('github actions', 'hub' )
        run: echo hub is true
      - name: contains with true
        if: contains('github, actions', 'hub' )
        run: echo hub is true
        
