name: env1.yml
on: push
# workflow레벨에서 환경 변수 정의 하기
# 환경 변수는 관례상 대문자 + _ 를 사용한다
env:
  KEY_NAME: workflow
  
jobs:
  get-env-1:
    runs-on: ubuntu-latest
    steps:
      - name: workflow level env
        run: |
          echo "LEVEL is ${{ env.KEY_NAME }}"
          echo "${{ env.KEY_NAME }} level env is any jobs, any steps available access"

  get-env-2:
    runs-on: ubuntu-latest
    env:
      KEY_NAME: job
    steps:
      - name: workflow level env
        run: |
          echo "LEVEL is ${{ env.KEY_NAME }}"
          echo "${{ env.KEY_NAME }} level env is this jobs, any steps available access"

  get-env-3:
    runs-on: ubuntu-latest
    env:
      KEY_NAME: step
    steps:
      - name: workflow level env
        env:
          KEY_NAME: step
        run: |
          echo "LEVEL is ${{ env.KEY_NAME }}"
          echo "${{ env.KEY_NAME }} level env is only this step available access"
  

  get-env:
    runs-on: ubuntu-latest
    steps:
      - name: create env like outputs
        run: echo "KEY_NAME=like outputs" >> $GITHUB_ENV
      - name: create env like outputs
        run: |
          echo "LEVEL is ${{ env.KEY_NAME }}"
          echo "${{ env.KEY_NAME }} level env is only this step available access"
          
          